project:
  type: website
  output-dir: docs

website:
  title: "Deep Reinforcement Learning"
  navbar:
    title: "Deep RL Course"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        menu:
          - text: "Introduction"
            href: "#introduction"
          - text: "Tabular RL"
            href: "#tabular-rl"
          - text: "Model-free RL"
            href: "#model-free-rl"
          - text: "Model-based RL"
            href: "#model-based-rl"
      - text: "Slides"
        menu:
          - text: "All Slides"
            href: "slides/"
          - text: "---"
          - text: "Introduction"
            href: "slides/0-Introduction.html"
          - text: "Bandits"
            href: "slides/1.1-Bandits.html"
          - text: "MDP"
            href: "slides/1.2-MDP.html"
      - text: "Book"
        menu:
          - text: "Introduction"
            href: "posts/0-Introduction.qmd"
          - text: "---"
          - text: "Tabular RL"
          - text: "Bandits"
            href: "posts/1.1-Bandits.qmd"
          - text: "MDP"
            href: "posts/1.2-MDP.qmd"
          - text: "Monte Carlo"
            href: "posts/1.3-MC.qmd"
          - text: "Temporal Difference"
            href: "posts/1.4-TD.qmd"
          - text: "Function Approximation"
            href: "posts/1.5-FunctionApproximation.qmd"
          - text: "Deep Networks"
            href: "posts/1.6-DeepNetworks.qmd"
          - text: "---"
          - text: "Model-free RL"
          - text: "DQN"
            href: "posts/2.1-DQN.qmd"
          - text: "DQN Variants"
            href: "posts/2.2-DQNvariants.qmd"
          - text: "Policy Gradient"
            href: "posts/2.3-PG.qmd"
          - text: "Actor-Critic"
            href: "posts/2.4-ActorCritic.qmd"
          - text: "DPG"
            href: "posts/2.5-DPG.qmd"
          - text: "PPO"
            href: "posts/2.6-PPO.qmd"
          - text: "SAC"
            href: "posts/2.8-SAC.qmd"
          - text: "---"
          - text: "Model-based RL"
          - text: "Model-based"
            href: "posts/3.1-ModelBased.qmd"
          - text: "Learned Models"
            href: "posts/3.2-LearnedModels.qmd"
          - text: "World Models"
            href: "posts/3.4-WorldModels.qmd"
          - text: "AlphaGo"
            href: "posts/3.5-AlphaGo.qmd"
          - text: "---"
          - text: "Outlook"
            href: "posts/4.1-Outlook.qmd"
      - text: "Resources"
        menu:
          - text: "GitHub Repository"
            href: "https://github.com/phatcvo/Lec-DRL"
          - text: "Bibliography"
            href: "#recommended-readings"
    right:
      - icon: github
        href: "https://github.com/phatcvo/Lec-DRL"
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: [assets/custom.scss, assets/homepage.scss]
    toc: true
    toc-location: left
    smooth-scroll: true
    link-external-newwindow: true
    code-fold: false
    code-tools: true
